-- 샘플 콘텐츠: 지역 2곳, 경험 10개.
-- src/data/*.sample.ts 에서 옮겼다 (문장은 임시 — 실제 데이터로 교체한다).
-- 사진이 아직 없어 image_urls 는 비어 있다. shorts_url 은 가짜 링크를 만들지 않으려고 모두 null.

insert into public.places
  (region, slug, name_en, area_en, tagline_en, headline_en, lead_en, description_en,
   card_tagline_en, hero_caption, card_caption, plan, day, is_published)
values
  ('gangneung',
   'gangneung',
   'Gangneung',
   'Gangwon · East Coast',
   'Coffee, coastal walks and slow mornings.',
   'A slower side of Korea.',
   'Make room for sea air, neighborhood cafés and everyday discoveries.',
   'Where the mountains meet the sea, Gangneung keeps a slower pace than the capital. Coffee roasters line the beach road, pine trails run right down to the water, and the fish markets are still working markets rather than sights. Two hours from Seoul by train, and a different country by the time you get off it.',
   'Coffee with a sea breeze',
   'Anmok Beach, Gangneung · 06:20',
   'Gyeongpo, Gangneung · 17:10',
   '[{"title_en":"Getting there","desc_en":"KTX from Seoul Station, about 2 hours to Gangneung Station."},{"title_en":"Best months","desc_en":"May to June and September to October. August is the busy month."},{"title_en":"Getting around","desc_en":"Local buses reach the coast; taxis are cheap for short hops."}]'::jsonb,
   '[{"title_en":"Start at the harbor","desc_en":"The market floor is busiest before seven, and quiet again by nine."},{"title_en":"Coffee on the beach road","desc_en":"Anmok has a row of roasters facing the water. Take the slow one."},{"title_en":"Walk the pine trail","desc_en":"The shore path runs north from Gyeongpo. An hour, flat the whole way."}]'::jsonb,
   true),
  ('seoul',
   'seoul',
   'Seoul',
   'Sudogwon · Han River',
   'The parts of the city the tour buses skip.',
   'Seoul, one street back.',
   'Not the landmarks — the neighborhoods people actually live in.',
   'Most trips to Korea start and end here, which is exactly why the interesting parts are easy to miss. Behind the main shopping streets are hillside neighborhoods, morning markets and workshops that have been in the same family for decades. These are the ones worth the detour.',
   'One street back from the crowds',
   'Ihwa-dong, Seoul · 08:15',
   'Seochon, Seoul · 19:40',
   '[{"title_en":"Getting there","desc_en":"Incheon Airport to the city center by AREX, about an hour."},{"title_en":"Best months","desc_en":"April to May and October. July and August are hot and wet."},{"title_en":"Getting around","desc_en":"The subway reaches almost everything. Buy a T-money card first."}]'::jsonb,
   '[{"title_en":"Morning on the hill","desc_en":"The old neighborhoods north of the palaces are quietest before ten."},{"title_en":"Lunch where the queue is","desc_en":"One-dish shops turn over fast. A short queue means a short wait."},{"title_en":"Evening by the water","desc_en":"The Han River parks fill up after work. That is the point of them."}]'::jsonb,
   true);

insert into public.experiences
  (slug, name_en, tagline_en, why_not_seoul_en, description_en, how_to_get_there_en,
   region, interest_tags, style_tags, duration, price_level, best_time,
   english_ease, localness, booking_required, map_url, image_urls, image_captions,
   shorts_url, related_slugs, is_published, created_at, updated_at)
values
  ('jumunjin-fish-market-dawn',
   'Jumunjin Fish Market at Dawn',
   'Watch the night''s catch come in before the town wakes up',
   'A working east-coast harbor market — Seoul''s markets sell what arrives here hours later',
   'Jumunjin is a small fishing port on the northern edge of Gangneung. Boats come back before sunrise, and by five the market floor is already wet, loud and busy. Squid, crab and flatfish are sorted in plastic tubs while traders call out prices to restaurant owners who have driven in from across the province.

Come early and walk slowly. Nobody minds if you just watch, and most stalls will point at a price on a cardboard sign if you ask. Around the edges, small restaurants will cook what you buy downstairs for a table fee. Breakfast here is raw fish, spicy fish stew or a bowl of rice with whatever came in that morning.

By nine the tour buses start to arrive and the mood changes. The quiet hour before that is the reason to come.',
   'KTX to Gangneung, then a local bus or taxi north along the coast (about 30 min)',
   'gangneung',
   array['food', 'local', 'sea']::text[],
   array['local_style']::text[],
   '1-2h',
   'low',
   'Year-round, 05:00–07:00',
   2,
   5,
   false,
   'https://www.google.com/maps/search/?api=1&query=Jumunjin%20Fish%20Market',
   '{}'::text[],
   array['Jumunjin, Gangneung · 05:40']::text[],
   null,
   array['anmok-beach-dawn-coffee', 'chodang-sundubu-breakfast', 'sogeumgang-valley-hike']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('daegwallyeong-sheep-farm',
   'Daegwallyeong Sheep Farm Walk',
   'A quiet hillside walk above the clouds',
   'Korea''s highlands — nothing like this exists near Seoul',
   'Daegwallyeong is the high pass that separates Gangneung from the mountains inland. Up here the air is cooler, the wind rarely stops, and on many mornings the valley below disappears under cloud. The sheep farm sits on a rounded ridge with a fenced path that loops through grazing fields.

The walk itself is gentle and takes under an hour, but most people stay longer. There is a small barn where you can feed the sheep hay, and a few benches facing east where you can watch the weather move over the ridges. After rain the grass turns a very deep green and the crowds thin out.

Bring a layer even in summer. It can be several degrees colder than on the coast, and the wind makes it feel colder still.',
   'Bus from Gangneung to Hoenggye, then a short taxi up the pass',
   'gangneung',
   array['nature']::text[],
   array['slow', 'active']::text[],
   'half-day',
   'low',
   'Spring–Autumn, morning',
   3,
   4,
   false,
   'https://www.google.com/maps/search/?api=1&query=Daegwallyeong%20Sheep%20Farm',
   '{}'::text[],
   array['Daegwallyeong · after rain']::text[],
   null,
   array['sogeumgang-valley-hike', 'ojukheon-house', 'anmok-beach-dawn-coffee']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('anmok-beach-dawn-coffee',
   'Anmok Beach Coffee Street at Sunrise',
   'Watch the East Sea turn pink with a cup from a local roaster',
   'Seoul has cafés; it doesn''t have a sunrise over open sea from the counter',
   'Anmok Beach is a short strip of sand south of Gangneung Port, lined with a long row of cafés facing the water. Years ago people came here for canned coffee from vending machines on the seawall. Now small roasters have taken over the buildings, and many open early for the sunrise.

Pick a window seat on an upper floor, or take a cup down to the sand. In late autumn and winter the sun comes up late enough that you do not need an alarm at four, and the beach is almost empty. Fishing boats cross the horizon while the light changes.

It is an easy morning with no plan. Walk the seawall afterwards toward the port and watch the ferries head out.',
   'KTX to Gangneung, then a taxi to Anmok Beach (about 15 min)',
   'gangneung',
   array['sea', 'food']::text[],
   array['slow', 'easy']::text[],
   '1-2h',
   'low',
   'Autumn–Winter, sunrise',
   4,
   3,
   false,
   'https://www.google.com/maps/search/?api=1&query=Anmok%20Beach%20Coffee%20Street',
   '{}'::text[],
   array['Anmok Beach · 06:10, Nov']::text[],
   null,
   array['jumunjin-fish-market-dawn', 'chodang-sundubu-breakfast', 'ojukheon-house']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('ojukheon-house',
   'Ojukheon, a Joseon Scholar''s Home',
   'Black bamboo and old wooden halls where Yulgok was born',
   'A family house in its own garden, not a palace rebuilt in the middle of traffic',
   'Ojukheon is the house where Yi I, a Joseon-era scholar better known as Yulgok, was born in the sixteenth century. His mother, Shin Saimdang, was a painter and poet, and both of them now appear on Korean banknotes. The name comes from the black bamboo that still grows around the grounds.

The main hall is one of the oldest wooden houses still standing in Korea. It is small, plain and quiet, which is exactly the point. Walk slowly through the courtyard, look at the roof lines against the pine trees, and then visit the small museum beside it.

Rainy mornings are the best time. The wood darkens, the bamboo moves in the wind, and school groups have not arrived yet.',
   'Local bus from Gangneung Station (about 20 min) or a short taxi',
   'gangneung',
   array['history']::text[],
   array['slow', 'easy']::text[],
   '1-2h',
   'low',
   'Year-round, morning',
   3,
   3,
   false,
   'https://www.google.com/maps/search/?api=1&query=Ojukheon%20Gangneung',
   '{}'::text[],
   array['Ojukheon · 09:00, rain']::text[],
   null,
   array['chodang-sundubu-breakfast', 'anmok-beach-dawn-coffee', 'daegwallyeong-sheep-farm']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('chodang-sundubu-breakfast',
   'Chodang Soft Tofu Breakfast',
   'Silky tofu made with seawater, eaten where it began',
   'Chodang tofu is set with East Sea water — it tastes different here',
   'Chodang is a neighborhood near Gyeongpo Lake known for one thing: sundubu, a soft, barely set tofu. Instead of a store-bought coagulant, local cooks have long used clean seawater to set the soy milk, which gives it a faint salty sweetness.

A whole street of family restaurants serves it. Order the white version first to taste the tofu itself, then try the red, spicy one if you want more heat. It comes with rice and a few side dishes. Many places open early and are full of locals before work.

After breakfast, walk to the pine forest at the edge of the lake. It is a good way to slow down before the rest of the day.',
   'KTX to Gangneung, then a taxi to Chodang-dong (about 15 min)',
   'gangneung',
   array['food', 'local']::text[],
   array['local_style', 'easy']::text[],
   '1-2h',
   'low',
   'Year-round, 07:00–09:00',
   2,
   5,
   false,
   'https://www.google.com/maps/search/?api=1&query=Chodang%20Sundubu%20Village%20Gangneung',
   '{}'::text[],
   array['Chodang-dong · 08:00']::text[],
   null,
   array['jumunjin-fish-market-dawn', 'ojukheon-house', 'anmok-beach-dawn-coffee']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('sogeumgang-valley-hike',
   'Sogeumgang Valley Hike',
   'Granite pools and waterfalls on the edge of Odaesan',
   'A real mountain valley with clear water — Seoul''s hills are close, but not like this',
   'Sogeumgang is a steep, rocky valley on the eastern side of Odaesan National Park, inside Gangneung''s borders. The trail follows a stream over pale granite, past deep green pools and a series of small waterfalls. The name means "little Geumgang", after the famous mountains in the north.

The lower section is an easy walk on a wide path and is fine for most people. Further in, the trail climbs harder toward the ridge, so decide how far to go before you start. In October the maples along the water turn red and orange, and weekday mornings are much quieter than weekends.

Bring water and food. There are only a few small shops near the entrance, and none on the trail.',
   'Bus from Gangneung to the Sogeumgang entrance (about 1 hour)',
   'gangneung',
   array['nature']::text[],
   array['active']::text[],
   'half-day',
   'free',
   'Autumn, morning',
   2,
   4,
   false,
   'https://www.google.com/maps/search/?api=1&query=Sogeumgang%20Valley',
   '{}'::text[],
   array['Sogeumgang · 07:30, Oct']::text[],
   null,
   array['daegwallyeong-sheep-farm', 'jumunjin-fish-market-dawn', 'ojukheon-house']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('mangwon-market-lunch',
   'Mangwon Market Lunch Crawl',
   'Snack your way through a market locals actually use',
   'Not Myeongdong — a daily market where people buy dinner, not souvenirs',
   'Mangwon Market sits in a residential neighborhood near the Han River, west of Hongdae. It is where people from the surrounding apartments buy vegetables, side dishes and fried chicken on the way home. Prices are written on cardboard and nothing is staged for visitors.

Go around lunchtime and eat standing up. Pick up fried dumplings from one stall, a paper cup of tteokbokki from another, and croquettes from a bakery near the entrance. Most vendors are used to pointing, and cards are widely accepted.

When you are full, walk to Mangwon Hangang Park and sit by the river. It is one of the easiest ways to see an ordinary Seoul afternoon.',
   'Subway Line 6 to Mangwon Station, then a 5-minute walk',
   'seoul',
   array['food', 'local']::text[],
   array['local_style', 'easy']::text[],
   '1-2h',
   'low',
   'Year-round, 11:30–14:00',
   3,
   4,
   false,
   'https://www.google.com/maps/search/?api=1&query=Mangwon%20Market%20Seoul',
   '{}'::text[],
   array['Mangwon Market · 12:30']::text[],
   null,
   array['euljiro-print-alleys', 'seochon-back-lanes', 'inwangsan-sunset-walk']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('inwangsan-sunset-walk',
   'Inwangsan Sunset Ridge Walk',
   'A short climb along the old city wall to watch Seoul light up',
   'The city looks small from up here — a reminder of how much Korea lies beyond it',
   'Inwangsan is a rocky hill on the western side of central Seoul, crossed by a restored section of the old city wall. The trail is mostly stone steps, steep in places, and reaches the top in about an hour.

From the summit you can see palace roofs, office towers and the mountains that ring the city. Arrive about an hour before sunset, find a rock to sit on and wait for the lights to come on below. On clear autumn evenings the ridges to the north turn blue one by one.

Bring a light for the way down and wear shoes with grip. The steps are uneven and can be slippery after rain.',
   'Subway Line 3 to Dongnimmun Station, then walk to the trailhead',
   'seoul',
   array['nature', 'history']::text[],
   array['active']::text[],
   '1-2h',
   'free',
   'Spring and Autumn, sunset',
   3,
   4,
   false,
   'https://www.google.com/maps/search/?api=1&query=Inwangsan%20Seoul',
   '{}'::text[],
   array['Inwangsan · 18:40, Sep']::text[],
   null,
   array['seochon-back-lanes', 'mangwon-market-lunch', 'euljiro-print-alleys']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('euljiro-print-alleys',
   'Euljiro Print Shop Alleys',
   'Old workshops, loud machines and bars hidden above them',
   'The Seoul that built everything else — still working, still unpolished',
   'Euljiro is a grid of narrow alleys in central Seoul filled with small print shops, lighting stores and metal workshops. Many have been run by the same families for decades. During the day, hand carts squeeze past and machines clatter behind half-open shutters.

Walk without a map. Look for stacks of paper on carts, neon signs made to order and staircases leading up to unmarked doors. In recent years some of those doors have become cafés and small bars, which fill up with office workers in the evening.

Be polite around the workshops. These are working places, so ask before taking photos of people, and step aside when a delivery comes through.',
   'Subway Line 2 or 3 to Euljiro 3-ga Station',
   'seoul',
   array['local', 'kculture']::text[],
   array['local_style', 'slow']::text[],
   '1-2h',
   'free',
   'Weekdays, late afternoon',
   2,
   5,
   false,
   'https://www.google.com/maps/search/?api=1&query=Euljiro%203-ga%20Seoul',
   '{}'::text[],
   array['Euljiro 3-ga · 16:00']::text[],
   null,
   array['mangwon-market-lunch', 'seochon-back-lanes', 'inwangsan-sunset-walk']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z'),
  ('seochon-back-lanes',
   'Seochon Back Lanes',
   'Hanok houses, tiny bookshops and a slower side of central Seoul',
   'Beside the palace crowds, a neighborhood where people still live in the old houses',
   'Seochon is the area just west of Gyeongbokgung Palace, between the palace wall and Inwangsan. Unlike the better-known hanok village on the other side of the palace, most houses here are ordinary homes, mixed with small galleries, bookshops and family restaurants.

Start at Tongin Market, where you can fill a lunch box with side dishes paid for with old-style brass coins. Then wander the lanes heading uphill. Look for tiled roofs, potted plants on doorsteps and cats asleep on the walls.

Weekend mornings are calm, and many shops open late, so there is time to walk before the cafés fill up. Keep your voice low; the people living here appreciate it.',
   'Subway Line 3 to Gyeongbokgung Station, then a 5-minute walk',
   'seoul',
   array['history', 'local']::text[],
   array['slow', 'easy']::text[],
   '1-2h',
   'free',
   'Year-round, weekend morning',
   4,
   3,
   false,
   'https://www.google.com/maps/search/?api=1&query=Seochon%20Seoul',
   '{}'::text[],
   array['Seochon · 10:00, Sun']::text[],
   null,
   array['inwangsan-sunset-walk', 'euljiro-print-alleys', 'mangwon-market-lunch']::text[],
   true,
   '2026-09-11T00:00:00Z',
   '2026-09-11T00:00:00Z');
